export const actionType = {
  SET_CAROUSEL: "SET_CAROUSEL",
  SET_DANH_SACH_PHIM: "SET_DANH_SACH_PHIM",
  SET_PHIM_DANG_CHIEU: "SET_PHIM_DANG_CHIEU",
  SET_PHIM_SAP_CHIEU: "SET_PHIM_SAP_CHIEU",
  SET_THONG_TIN_PHIM: "SET_THONG_TIN_PHIM",
};
